main:
  - name: About
    url: /#about
    weight: 10
  - name: Publications
    url: /#publications
    weight: 20
  - name: Software
    url: /#software
    weight: 30
  - name: Artworks
    url: /#artworks
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
