main:
  - name: About
    url: /#about
    weight: 10
  - name: Publications
    url: /#publications
    weight: 20
  - name: Artworks
    url: /#artworks
    weight: 30
  - name: Contact
    url: /#contact
    weight: 40
